name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Frontend
        run: |
          cd frontend
          # Add build commands specific to your frontend project
          # For example, if you're using npm:
          # npm install
          # npm run build
          # Or if you're using yarn:
          # yarn install
          # yarn build

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          git rm -rf .
          cp -r frontend/dist/* .
          git add .
          git commit -m "Update GitHub Pages"
          git push origin gh-pages
